# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
Ls <- function(w) {
    .Call('_graph2graph_Ls', PACKAGE = 'graph2graph', w)
}

colwise_norms <- function(M) {
    .Call('_graph2graph_colwise_norms', PACKAGE = 'graph2graph', M)
}

